import {useEffect,useState} from 'react';
export default function Admin(){const[token,setToken]=useState(null);const[password,setPassword]=useState('');const[projects,setProjects]=useState([]);const[form,setForm]=useState({title:'',description:'',year:'',image:''});const[editingId,setEditingId]=useState(null);const[uploading,setUploading]=useState(false);
useEffect(()=>{const t=localStorage.getItem('sf_token');if(t){setToken(t);loadProjects(t)}},[]);
async function login(e){e.preventDefault();const res=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(res.ok){const j=await res.json();localStorage.setItem('sf_token',j.token);setToken(j.token);loadProjects(j.token)}else alert('비밀번호 오류');}
async function loadProjects(t){const r=await fetch('/api/projects',{headers:{'x-admin-token':t}});if(r.ok){setProjects(await r.json());}}
function resetForm(){setForm({title:'',description:'',year:'',image:''});setEditingId(null);}
async function saveProject(e){e.preventDefault();const method=editingId?'PUT':'POST';const body=editingId?{...form,id:editingId}:form;const r=await fetch('/api/projects',{method,headers:{'Content-Type':'application/json','x-admin-token':token},body:JSON.stringify(body)});if(r.ok){await loadProjects(token);resetForm();}}
function editProject(p){setEditingId(p.id);setForm({title:p.title,description:p.description,year:p.year,image:p.image});}
async function del(id){if(!confirm('삭제?'))return;const r=await fetch('/api/projects',{method:'DELETE',headers:{'Content-Type':'application/json','x-admin-token':token},body:JSON.stringify({id})});if(r.ok)loadProjects(token);}
async function handleFile(e){const f=e.target.files?.[0];if(!f)return;setUploading(true);const fd=new FormData();fd.append('file',f);const r=await fetch('/api/upload',{method:'POST',body:fd});const j=await r.json();if(r.ok){setForm({...form,image:j.url});}else alert('업로드 실패');setUploading(false);}
if(!token)return(<div style={{padding:20}}><h2>Admin Login</h2><form onSubmit={login}><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" type="password"/><button>Login</button></form></div>);
return(<div style={{padding:20}}><h2>Admin - Projects (Cloudinary)</h2><form onSubmit={saveProject} style={{marginBottom:20}}><input placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><input placeholder="Year" value={form.year} onChange={e=>setForm({...form,year:e.target.value})} required/><label>이미지 업로드<input type="file" accept="image/*" onChange={handleFile}/></label><input placeholder="Image URL" value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/>{uploading&&<p>업로드 중...</p>}<textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button type="submit">{editingId?'Update':'Add'}</button><button type="button" onClick={resetForm}>Reset</button></form><div>{projects.map(p=>(<div key={p.id} style={{border:'1px solid #ddd',padding:10,marginBottom:8}}><strong>{p.title} ({p.year})</strong><div style={{marginTop:8}}><button onClick={()=>editProject(p)}>Edit</button><button onClick={()=>del(p.id)} style={{marginLeft:8}}>Delete</button></div></div>))}</div></div>);}
